PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS Admin (
  id TEXT PRIMARY KEY NOT NULL,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'ADMIN',
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS User (
  id TEXT PRIMARY KEY NOT NULL,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  phone TEXT,
  country TEXT,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS Program (
  id TEXT PRIMARY KEY NOT NULL,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  type TEXT NOT NULL,
  description TEXT NOT NULL,
  priceIndia INTEGER NOT NULL,
  priceGlobal INTEGER NOT NULL,
  currencyIndia TEXT NOT NULL DEFAULT 'INR',
  currencyGlobal TEXT NOT NULL DEFAULT 'USD',
  schedule TEXT NOT NULL,
  zoomLink TEXT,
  duration TEXT,
  active BOOLEAN NOT NULL DEFAULT 1,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS Batch (
  id TEXT PRIMARY KEY NOT NULL,
  programId TEXT NOT NULL,
  startsAt DATETIME NOT NULL,
  capacity INTEGER NOT NULL,
  zoomLink TEXT,
  active BOOLEAN NOT NULL DEFAULT 1,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL,
  FOREIGN KEY (programId) REFERENCES Program(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Booking (
  id TEXT PRIMARY KEY NOT NULL,
  bookingReference TEXT NOT NULL UNIQUE,
  userId TEXT,
  programId TEXT NOT NULL,
  batchId TEXT,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  country TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'PENDING',
  attendanceStatus TEXT NOT NULL DEFAULT 'NOT_MARKED',
  notes TEXT,
  amount INTEGER NOT NULL,
  currency TEXT NOT NULL,
  registeredAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE SET NULL ON UPDATE CASCADE,
  FOREIGN KEY (programId) REFERENCES Program(id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (batchId) REFERENCES Batch(id) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Payment (
  id TEXT PRIMARY KEY NOT NULL,
  bookingId TEXT NOT NULL UNIQUE,
  provider TEXT NOT NULL,
  transactionId TEXT NOT NULL UNIQUE,
  amount INTEGER NOT NULL,
  currency TEXT NOT NULL,
  status TEXT NOT NULL,
  paidAt DATETIME,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL,
  FOREIGN KEY (bookingId) REFERENCES Booking(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Testimonial (
  id TEXT PRIMARY KEY NOT NULL,
  name TEXT NOT NULL,
  country TEXT NOT NULL,
  content TEXT NOT NULL,
  category TEXT NOT NULL,
  featured BOOLEAN NOT NULL DEFAULT 0,
  active BOOLEAN NOT NULL DEFAULT 1,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS ContactRequest (
  id TEXT PRIMARY KEY NOT NULL,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT,
  message TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'NEW',
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS EmailTemplate (
  id TEXT PRIMARY KEY NOT NULL,
  key TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  subject TEXT NOT NULL,
  body TEXT NOT NULL,
  active BOOLEAN NOT NULL DEFAULT 1,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS EmailLog (
  id TEXT PRIMARY KEY NOT NULL,
  recipient TEXT NOT NULL,
  templateId TEXT,
  bookingId TEXT,
  subject TEXT NOT NULL,
  status TEXT NOT NULL,
  sentAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  error TEXT,
  FOREIGN KEY (templateId) REFERENCES EmailTemplate(id) ON DELETE SET NULL ON UPDATE CASCADE,
  FOREIGN KEY (bookingId) REFERENCES Booking(id) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS PaymentLog (
  id TEXT PRIMARY KEY NOT NULL,
  paymentId TEXT,
  transactionId TEXT NOT NULL,
  amount INTEGER NOT NULL,
  currency TEXT NOT NULL,
  status TEXT NOT NULL,
  payload TEXT,
  timestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (paymentId) REFERENCES Payment(id) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Attendance (
  id TEXT PRIMARY KEY NOT NULL,
  bookingId TEXT NOT NULL UNIQUE,
  batchId TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'NOT_MARKED',
  markedAt DATETIME,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL,
  FOREIGN KEY (bookingId) REFERENCES Booking(id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (batchId) REFERENCES Batch(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS SystemConfig (
  id TEXT PRIMARY KEY NOT NULL,
  key TEXT NOT NULL UNIQUE,
  value TEXT NOT NULL,
  "group" TEXT NOT NULL,
  secret BOOLEAN NOT NULL DEFAULT 0,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL
);
