import type React from "react";
import { Activity, Database, Mail, Shield, Video, Wallet } from "lucide-react";
import { prisma } from "@/lib/prisma";
import { metadataMap } from "@/lib/admin-metadata";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { updateConfig } from "../../orientation-settings/actions";

export const dynamic = "force-dynamic";
export const revalidate = 0;

const get = (config: Record<string, string>, key: string, fallback = "") => config[key] ?? fallback;

export default async function ServerConfigPage() {
  const configs = await prisma.systemConfig.findMany({ orderBy: [{ group: "asc" }, { key: "asc" }] });
  const config = metadataMap(configs);
  const health = [
    ["Database", "Healthy"], ["Payment Gateway", "Warning"], ["Zoom", "Healthy"], ["Email Service", "Healthy"], ["WhatsApp", "Warning"], ["Storage", "Healthy"], ["Background Jobs", "Healthy"]
  ];

  return (
    <div className="space-y-6">
      <div><p className="text-sm font-semibold uppercase tracking-widest text-accent">System Configuration</p><h1 className="font-serif text-4xl font-bold">Environment Settings</h1><p className="mt-2 text-sm text-muted-foreground">Manage application integrations, credentials, automation settings, and platform configuration.</p></div>
      <div className="grid gap-4 md:grid-cols-6"><Stat icon={<Activity className="h-5 w-5" />} title="System Status" value="Healthy" /><Stat icon={<Wallet className="h-5 w-5" />} title="Active Integrations" value="5" /><Stat icon={<Activity className="h-5 w-5" />} title="Scheduled Jobs" value="6" /><Stat icon={<Mail className="h-5 w-5" />} title="Email Health" value="Healthy" /><Stat icon={<Wallet className="h-5 w-5" />} title="Payment Health" value="Warning" /><Stat icon={<Video className="h-5 w-5" />} title="Zoom Status" value="Healthy" /></div>
      <form action={updateConfig} className="space-y-6">
        <div className="flex flex-wrap gap-2">{["System", "Payments", "Zoom", "Email", "WhatsApp", "Automation", "Security", "Backups", "Storage", "Analytics", "SEO", "Health"].map((tab) => <a key={tab} href={`#${tab.toLowerCase()}`} className="rounded-md border px-3 py-2 text-sm hover:bg-muted">{tab}</a>)}</div>
        <Section id="system" title="System Configuration" description="Application defaults and public support details."><Grid><InputField name="application_name" label="Application Name" value={get(config, "application_name", "iChaitanya")} /><InputField name="organization_name" label="Organization Name" value={get(config, "organization_name", "iChaitanya")} /><InputField name="support_email" label="Support Email" value={get(config, "support_email", "support@ichaitanya.com")} /><InputField name="support_whatsapp" label="Support WhatsApp" value={get(config, "whatsapp_number", "+91 92176 39689")} /><InputField name="website_url" label="Website URL" value={get(config, "website_url", "http://localhost:3000")} /><InputField name="default_timezone" label="Default Timezone" value={get(config, "default_timezone", "Asia/Kolkata")} /><InputField name="default_currency" label="Default Currency" value={get(config, "default_currency", "INR")} /></Grid></Section>
        <Section id="payments" title="Payment Settings" description="Razorpay, PayPal, modes, webhooks, and connection checks."><Grid><Toggle name="razorpay_enabled" label="Enable Razorpay" checked={get(config, "razorpay_enabled", "true") === "true"} /><InputField name="razorpay_key_id" label="Razorpay Key ID" value={get(config, "razorpay_key_id")} /><Secret name="razorpay_key_secret" label="Razorpay Secret Key" value={get(config, "razorpay_key_secret")} /><Secret name="razorpay_webhook_secret" label="Razorpay Webhook Secret" value={get(config, "razorpay_webhook_secret")} /><Toggle name="razorpay_test_mode" label="Razorpay Test Mode" checked={get(config, "razorpay_test_mode", "true") === "true"} /><Button type="button" variant="outline">Test Razorpay Connection</Button><Toggle name="paypal_enabled" label="Enable PayPal" checked={get(config, "paypal_enabled", "true") === "true"} /><InputField name="paypal_client_id" label="PayPal Client ID" value={get(config, "paypal_client_id")} /><Secret name="paypal_client_secret" label="PayPal Secret" value={get(config, "paypal_client_secret")} /><Toggle name="paypal_sandbox" label="PayPal Sandbox Mode" checked={get(config, "paypal_sandbox", "true") === "true"} /><Button type="button" variant="outline">Test PayPal Connection</Button></Grid></Section>
        <Section id="zoom" title="Zoom Settings" description="Integration credentials and default meeting behavior."><Grid><Toggle name="zoom_enabled" label="Enable Zoom Integration" checked={get(config, "zoom_enabled", "true") === "true"} /><InputField name="zoom_account_email" label="Account Email" value={get(config, "zoom_account_email")} /><InputField name="zoom_client_id" label="Client ID" value={get(config, "zoom_client_id")} /><Secret name="zoom_client_secret" label="Client Secret" value={get(config, "zoom_client_secret")} /><Secret name="zoom_webhook_secret" label="Webhook Secret" value={get(config, "zoom_webhook_secret")} /><InputField name="zoom_meeting_duration" label="Meeting Duration" value={get(config, "zoom_meeting_duration", "40")} /><Toggle name="zoom_waiting_room" label="Waiting Room" checked={get(config, "zoom_waiting_room", "true") === "true"} /><Toggle name="zoom_record_sessions" label="Record Sessions" checked={get(config, "zoom_record_sessions") === "true"} /><Toggle name="zoom_auto_create" label="Auto Create Meeting" checked={get(config, "zoom_auto_create", "true") === "true"} /><Button type="button" variant="outline">Test Zoom Connection</Button></Grid></Section>
        <Section id="email" title="Email Settings" description="SMTP, Resend, SendGrid, Mailgun provider settings."><Grid><Select name="email_provider" label="Provider" value={get(config, "email_provider", "SMTP")} options={["SMTP", "Resend", "SendGrid", "Mailgun"]} /><InputField name="smtp_host" label="Host" value={get(config, "smtp_host")} /><InputField name="smtp_port" label="Port" value={get(config, "smtp_port", "587")} /><InputField name="smtp_user" label="Username" value={get(config, "smtp_user")} /><Secret name="smtp_password" label="Password" value={get(config, "smtp_password")} /><InputField name="from_name" label="From Name" value={get(config, "from_name", "iChaitanya")} /><InputField name="from_email" label="From Email" value={get(config, "from_email")} /><InputField name="reply_to_email" label="Reply-To Email" value={get(config, "reply_to_email")} /><Button type="button" variant="outline">Send Test Email</Button><Button type="button" variant="outline">Verify Connection</Button></Grid></Section>
        <Section id="whatsapp" title="WhatsApp Settings" description="Meta Cloud API, Twilio, or custom API configuration."><Grid><Toggle name="whatsapp_enabled" label="Enable WhatsApp" checked={get(config, "whatsapp_enabled") === "true"} /><Select name="whatsapp_provider" label="Provider" value={get(config, "whatsapp_provider", "Meta Cloud API")} options={["Meta Cloud API", "Twilio", "Custom API"]} /><InputField name="whatsapp_phone" label="Phone Number" value={get(config, "whatsapp_number")} /><Secret name="whatsapp_access_token" label="Access Token" value={get(config, "whatsapp_access_token")} /><InputField name="whatsapp_webhook_url" label="Webhook URL" value={get(config, "whatsapp_webhook_url")} /><Button type="button" variant="outline">Send Test Message</Button><Button type="button" variant="outline">Verify Connection</Button></Grid></Section>
        <Section id="automation" title="Automation Settings" description="Scheduled jobs, run windows, and status."><Grid><Toggle name="jobs_enabled" label="Enable Scheduled Jobs" checked={get(config, "jobs_enabled", "true") === "true"} />{["booking_confirmation", "session_reminder", "aura_night_reminder", "attendance_followup", "certificate_generation", "testimonial_request"].map((job) => <InputField key={job} name={`job_${job}`} label={job.replaceAll("_", " ")} value={get(config, `job_${job}`, "ACTIVE | Last: today | Next: next hour")} />)}</Grid></Section>
        <Section id="security" title="Security Settings" description="Admin login, MFA, policies, whitelist, and audit logging."><Grid><InputField name="session_timeout" label="Session Timeout" value={get(config, "session_timeout", "8 hours")} /><InputField name="password_policy" label="Password Policy" value={get(config, "password_policy", "12 chars, mixed")} /><Toggle name="mfa_required" label="MFA Requirement" checked={get(config, "mfa_required") === "true"} /><Textarea name="admin_login_restrictions" defaultValue={get(config, "admin_login_restrictions")} placeholder="Admin Login Restrictions" /><Textarea name="ip_whitelist" defaultValue={get(config, "ip_whitelist")} placeholder="IP Whitelist" /><Toggle name="audit_logging" label="Audit Logging" checked={get(config, "audit_logging", "true") === "true"} /></Grid></Section>
        <Section id="backups" title="Backup Settings" description="Database backup schedule, retention, and restore controls."><Grid><Select name="backup_frequency" label="Database Backup" value={get(config, "backup_frequency", "Daily")} options={["Daily", "Weekly", "Monthly"]} /><InputField name="backup_retention" label="Retention Period" value={get(config, "backup_retention", "30 days")} /><Button type="button" variant="outline">Manual Backup</Button><Button type="button" variant="outline">Restore Backup</Button></Grid></Section>
        <Section id="storage" title="Storage Settings" description="Local, S3, R2, upload size, and file types."><Grid><Select name="storage_provider" label="File Upload Storage" value={get(config, "storage_provider", "Local Storage")} options={["Local Storage", "AWS S3", "Cloudflare R2"]} /><InputField name="max_upload_size" label="Maximum Upload Size" value={get(config, "max_upload_size", "25MB")} /><InputField name="allowed_file_types" label="Allowed File Types" value={get(config, "allowed_file_types", "jpg,png,pdf,mp4")} /></Grid></Section>
        <Section id="analytics" title="Analytics Settings" description="Tracking pixels and verification status."><Grid>{["google_analytics", "google_tag_manager", "meta_pixel", "linkedin_insight"].map((name) => <InputField key={name} name={name} label={name.replaceAll("_", " ")} value={get(config, name)} />)}<Toggle name="analytics_enabled" label="Enable Analytics" checked={get(config, "analytics_enabled") === "true"} /></Grid></Section>
        <Section id="seo" title="SEO Settings" description="Default metadata, robots, sitemap, and canonical URL."><Grid><InputField name="default_meta_title" label="Default Meta Title" value={get(config, "default_meta_title", "iChaitanya")} /><Textarea name="default_meta_description" defaultValue={get(config, "default_meta_description")} placeholder="Default Meta Description" /><Textarea name="robots_config" defaultValue={get(config, "robots_config", "User-agent: *\nAllow: /")} placeholder="Robots Configuration" /><Toggle name="sitemap_generation" label="Sitemap Generation" checked={get(config, "sitemap_generation", "true") === "true"} /><InputField name="canonical_url" label="Canonical URL" value={get(config, "canonical_url")} /></Grid></Section>
        <Section id="health" title="System Health Dashboard" description="Integration status overview and audit history."><div className="grid gap-3 md:grid-cols-3">{health.map(([service, status]) => <div key={service} className="rounded-lg border p-4"><p className="text-sm text-muted-foreground">{service}</p><p className={status === "Healthy" ? "text-green-700" : "text-orange-700"}>{status}</p></div>)}</div><div className="mt-4 rounded-lg border p-4"><p className="font-semibold">Audit Log</p><p className="mt-2 text-sm text-muted-foreground">Configuration changes, credential updates, integration changes, security changes, actor, and timestamp are tracked through SystemConfig update metadata in this no-migration pass.</p></div></Section>
        <Button variant="accent">Save System Configuration</Button>
      </form>
    </div>
  );
}

function Stat({ icon, title, value }: { icon: React.ReactNode; title: string; value: string }) { return <Card><CardContent className="p-5"><div className="mb-3 flex h-9 w-9 items-center justify-center rounded-md bg-accent/10 text-accent">{icon}</div><p className="text-sm text-muted-foreground">{title}</p><p className="mt-2 font-bold">{value}</p></CardContent></Card>; }
function Section({ id, title, description, children }: { id: string; title: string; description: string; children: React.ReactNode }) { return <Card id={id}><CardHeader><CardTitle>{title}</CardTitle><CardDescription>{description}</CardDescription></CardHeader><CardContent>{children}</CardContent></Card>; }
function Grid({ children }: { children: React.ReactNode }) { return <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{children}</div>; }
function InputField({ name, label, value }: { name: string; label: string; value: string }) { return <label className="grid gap-1 text-sm"><span className="font-medium capitalize">{label}</span><Input name={name} defaultValue={value} /></label>; }
function Secret({ name, label, value }: { name: string; label: string; value: string }) { return <label className="grid gap-1 text-sm"><span className="font-medium">{label}</span><Input name={name} type="password" defaultValue={value} /></label>; }
function Toggle({ name, label, checked }: { name: string; label: string; checked: boolean }) { return <label className="flex items-center gap-2 rounded-md border px-3 py-2 text-sm"><input name={name} type="checkbox" defaultChecked={checked} /> {label}</label>; }
function Select({ name, label, value, options }: { name: string; label: string; value: string; options: string[] }) { return <label className="grid gap-1 text-sm"><span className="font-medium">{label}</span><select name={name} defaultValue={value} className="h-10 rounded-md border bg-background px-3 text-sm">{options.map((option) => <option key={option}>{option}</option>)}</select></label>; }
